### ISSUE TITLE
[BUG] Crash when providing an int tag directly to a cfngin stack definition

### ISSUE THREAD

**Issue by jake-skipper** [rackspace/runway#1972]
### Bug Description

Providing a tag such as `CostCenter: 1234` and passing it directly in to a cfngin stack causes a crash due to Boto doing type validation on tag values (and only allowing `str`). This does not occur when using the top level `tags` field.

For instance, this works without issues:
```yaml
namespace: ${namespace}
cfngin_bucket: ""

tags:
  CostCenter: 1234

stacks:
  example-stack:
    template_path: template.yaml
```

And this will crash with a type error:
```yaml
namespace: ${namespace}
cfngin_bucket: ""

stacks:
  example-stack:
    template_path: template.yaml
    tags:
      CostCenter: 1234
```

We should probably determine what type of `int` to `str` conversion is happening to the top level `tags` field and apply the same to the stack level `tags` field.

In the meantime, a workaround is to quote the offending tag:
```yaml
namespace: ${namespace}
cfngin_bucket: ""

stacks:
  example-stack:
    template_path: template.yaml
    tags:
      CostCenter: "1234"
```

### Expected Behavior

Tag value handling at the stack level should be the same as the top level `tags` field.

### Steps To Reproduce

Already provided in description.

### Runway version

2.6.7

### Installation Type

pypi (pip, pipenv, poetry, etc)

### OS / Environment

N/A

### Anything else?

N/A
