### ISSUE TITLE
[REQUEST] There should be an option to incorporate runway actions into`tests` for post deploy testing

### ISSUE THREAD

**Issue by ITProKyle** [rackspace/runway#304]
Occasionally, there is need to validate the functionality of deployed, common infrastructure before being released for use. We should have a built-in test type to simplify this.

# Preliminary concept

The test type should act as a sort of context manager so that at the end of testing the infrastructure is always destroyed, even in the event of failures.

```yaml
tests:
  - name: module/deployment based selection
    type: runway
    args:
      module: deployment_1.sampleapp-cfn  # should this be a list?
      # deployment: deployment_1
      tests:  # potential way to defined multiple tests to run
        - runway_tests.sampleapp-cfn.Runner  # path to importable python class
      # or maybe test_runner: runway_tests.sampleapp-cfn
  - name: tag based selection
    type: runway
    args:
      tags:  # acts as "HAS tag1 AND tag2" just like when used from the cli 
        - app
      test_runner: runway_tests.sampleapp-cfn  # potential way to define. calls Runner.run()

deployments:
  - name: deployment_1
    modules:
      - sampleapp-cfn
    regions:
      - us-east-1
  - name: deployment_2
    modules:
      - path: sampleapp-cfn
        tags:
          - app
    regions:
      - us-east-1
```

## Steps taken when run

1. `runway deploy`
2. Import the test runner class and execute (passing in some args that are TBD) `runway_tests.sampleapp-cfn.Runner.run(**kwargs)`. The test runner class could be similar to our integration test runner
3. `runway destroy`
