### ISSUE TITLE
[REQUEST] k8s: support using jinja templates as kustomize overlays

### ISSUE THREAD

**Issue by leon-xz** [rackspace/runway#969]
Native k8s kustomize only support static overlay. Some tricks can be played with kustomize configmap/secret generator to pull environment variables into configmap/secret. However configmap/secret generator can only pass variables to pod, not other k8s services (eg. serviceaccount, service, ingress). Right now we have no way to dynamically config annotations with those non-pod resources, and annotations are frequently used in IAM role mapping, ingress settings.

It would be fantastic to have runway k8s support jinja template. Being able to use jinja template will allow us to dynamically config kustomize overlays (for all k8s resources, not limited to configmap/secrets)

Here is a sample overlay patch template we wish to have, allow us to dynamically pull AWS AccountID and Region into the template.

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: amazon-cloudwatch
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ account_id }}:role/eks-pod-role-fluentd-dev

apiVersion: v1
data:
  cluster.name: "ekslab-dev-k8s-cluster"
  http.port: "2020"
  http.server: "On"
  logs.region: "{{ region }}"
  read.head: "Off"
  read.tail: "On"
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
```
